# Generated by Django 5.1.6 on 2025-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=260)),
                ('author', models.CharField(max_length=260)),
                ('geo_entered', models.CharField(default='US', max_length=2)),
                ('entered_date', models.DateTimeField(verbose_name='date entered')),
                ('giveaway_ends_data', models.DateTimeField(verbose_name='giveaway end date')),
                ('entered', models.BooleanField(default=False)),
                ('format', models.CharField(default='print', max_length=20)),
            ],
        ),
    ]
